version: "3"

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - ./app/database.db/:/app/database.db/
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./app/database.db/:/app/database.db/
    depends_on:
      - sqlite3